BBFILES += "${LAYERDIR}/recipes/*/*.bb ${LAYERDIR}/recipes/*/*.bbappend"
BBPATH .= ":${LAYERDIR}"
BBFILE_COLLECTIONS += "qti-agm"
BBFILE_PRIORITY_qti-agm = "15"
BBFILE_PATTERN_qti-agm := "^${LAYERDIR}/"
LAYERSERIES_COMPAT_qti-agm = "dunfell"
LAYERDEPENDS_qti-agm := "\
   qti-audio \
   qti-args \
   qti-bsp \
   core"
LAYERSERIES_COMPAT_qti-agm = "dunfell"
LAYERVERSION_qti-agm = "1"
