#!/bin/sh /etc/rc.common

#Copyright (c) 2023 Qualcomm Technologies, Inc. All Rights Reserved.
#SPDX-License-Identifier: BSD-3-Clause-Clear.


START=34
STOP=65


USE_PROCD=1

start_service() {
	procd_open_instance
	echo "Start agm_server:" > /dev/kmsg
	procd_set_param command /usr/bin/agm_server
	procd_set_param respawn
	procd_set_param user root
	procd_set_param group root
	procd_close_instance
}

stop_service() {
	echo "Stopping agm_sw_binder_server:" > /dev/kmsg
	# commands to kill application
}
