#!/bin/sh /etc/rc.common

#Copyright (c) 2023 Qualcomm Technologies, Inc. All Rights Reserved.
#SPDX-License-Identifier: BSD-3-Clause-Clear.


START=34
STOP=65


USE_PROCD=1

start_service() {
	procd_open_instance
	echo "Start agm_server:" > /dev/kmsg
	procd_set_param command /usr/bin/agm_server
	procd_set_param respawn
	if [ -x /sbin/ujail -a -e /etc/capabilities/agm_server.json ]; then
		echo "UJAIL capabilities set for  agm_server:" > /dev/kmsg
		procd_set_param capabilities  /etc/capabilities/agm_server.json
		procd_add_jail agm_server
		procd_set_param user media
		procd_set_param group media
		procd_set_param no_new_privs 1
	fi
	procd_close_instance
}

stop_service() {
	echo "Stopping agm_sw_binder_server:" > /dev/kmsg
	# commands to kill application
}
